# These are supported funding model platforms

github: [i7poxop] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [i7poxop, user2]
custom: ['http://github.com/i7poxop'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
